apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: a8s-backend-namespace-manager
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs:
      - get
      - list
      - create
      - update
      - patch